### POST request to create user
POST http://lb-b6f34ce6.elb.localhost.localstack.cloud:4004/api/patients
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Ramefdshxx Stargirl",
  "email": "lmaosdfsd@yahoxx.com",
  "address": "abcsd msvdain st",
  "dateOfBirth": "1993-01-01",
  "registeredDate": "1999-01-01"
}

###